name: Build MoirAI on push

on:
  push:
    branches:
      - '**'
  workflow_dispatch:

jobs:
  MoirAI:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v6.0.2
        with:
          fetch-depth: 0

      - name: Set up Node
        uses: actions/setup-node@v4.4.0
        with:
          node-version: "22"

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Typecheck
        run: yarn typecheck

      - name: Lint
        run: yarn lint

      - name: Build
        run: yarn build
